//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

library openapi.api;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:collection/collection.dart';
import 'package:http/http.dart';
import 'package:intl/intl.dart';
import 'package:meta/meta.dart';

part 'api_client.dart';
part 'api_helper.dart';
part 'api_exception.dart';
part 'auth/authentication.dart';
part 'auth/api_key_auth.dart';
part 'auth/oauth.dart';
part 'auth/http_basic_auth.dart';
part 'auth/http_bearer_auth.dart';

part 'api/entitlements_api.dart';
part 'api/groups_api.dart';
part 'api/licenses_api.dart';
part 'api/machines_api.dart';
part 'api/passwords_api.dart';
part 'api/policies_api.dart';
part 'api/processes_api.dart';
part 'api/products_api.dart';
// BEGIN MANUALLY MODIFIED AFTER OPENAPI-GENERATOR RAN
part 'api/profiles_api.dart';
// END MANUALLY MODIFIED AFTER OPENAPI-GENERATOR RAN
part 'api/second_factors_api.dart';
part 'api/tokens_api.dart';
part 'api/users_api.dart';
// BEGIN MANUALLY MODIFIED AFTER OPENAPI-GENERATOR RAN
part 'api/webhooks_api.dart';
// END MANUALLY MODIFIED AFTER OPENAPI-GENERATOR RAN

part 'model/activate_machine_request.dart';
part 'model/activate_machine_request_data.dart';
part 'model/activate_machine_request_data_attributes.dart';
part 'model/activate_machine_request_data_relationships.dart';
part 'model/activate_machine_request_data_relationships_license.dart';
part 'model/activate_machine_request_data_relationships_license_data.dart';
part 'model/activate_machine_response.dart';
part 'model/add_second_factor_request.dart';
part 'model/add_second_factor_request_meta.dart';
part 'model/add_second_factor_response.dart';
part 'model/attach_license_entitlements_request.dart';
part 'model/attach_license_entitlements_response.dart';
part 'model/attach_policy_entitlements_request.dart';
part 'model/attach_policy_entitlements_request_data_inner.dart';
part 'model/attach_policy_entitlements_response.dart';
part 'model/ban_user_response.dart';
part 'model/change_license_group_request.dart';
part 'model/change_license_group_response.dart';
part 'model/change_license_policy_request.dart';
part 'model/change_license_policy_response.dart';
part 'model/change_license_user_request.dart';
part 'model/change_license_user_response.dart';
part 'model/change_machine_group_request.dart';
part 'model/change_machine_group_response.dart';
part 'model/change_user_group_request.dart';
part 'model/change_user_group_response.dart';
part 'model/check_in_license_response.dart';
part 'model/check_out_license_response.dart';
part 'model/check_out_machine_response.dart';
part 'model/create_entitlement_request.dart';
part 'model/create_entitlement_request_data.dart';
part 'model/create_entitlement_request_data_attributes.dart';
part 'model/create_entitlement_response.dart';
part 'model/create_group_request.dart';
part 'model/create_group_request_data.dart';
part 'model/create_group_request_data_attributes.dart';
part 'model/create_group_response.dart';
part 'model/create_license_request.dart';
part 'model/create_license_request_data.dart';
part 'model/create_license_request_data_attributes.dart';
part 'model/create_license_request_data_relationships.dart';
part 'model/create_license_request_data_relationships_group.dart';
part 'model/create_license_request_data_relationships_policy.dart';
part 'model/create_license_request_data_relationships_policy_data.dart';
part 'model/create_license_request_data_relationships_user.dart';
part 'model/create_license_request_data_relationships_user_data.dart';
part 'model/create_license_response.dart';
part 'model/create_license_token_request.dart';
part 'model/create_license_token_request_data.dart';
part 'model/create_license_token_request_data_attributes.dart';
part 'model/create_license_token_response.dart';
part 'model/create_policy_request.dart';
part 'model/create_policy_request_data.dart';
part 'model/create_policy_request_data_attributes.dart';
part 'model/create_policy_request_data_relationships.dart';
part 'model/create_policy_request_data_relationships_product.dart';
part 'model/create_policy_request_data_relationships_product_data.dart';
part 'model/create_policy_response.dart';
part 'model/create_product_request.dart';
part 'model/create_product_request_data.dart';
part 'model/create_product_request_data_attributes.dart';
part 'model/create_product_response.dart';
part 'model/create_user_request.dart';
part 'model/create_user_request_data.dart';
part 'model/create_user_request_data_attributes.dart';
part 'model/create_user_request_data_relationships.dart';
part 'model/create_user_request_data_relationships_group.dart';
part 'model/create_user_request_data_relationships_group_data.dart';
part 'model/create_user_response.dart';
part 'model/decrement_license_usage_request.dart';
part 'model/decrement_license_usage_request_meta.dart';
part 'model/decrement_license_usage_response.dart';
part 'model/detach_license_entitlements_request.dart';
part 'model/detach_policy_entitlements_request.dart';
part 'model/entitlement.dart';
part 'model/entitlement_attributes.dart';
part 'model/entitlement_relationships.dart';
part 'model/entitlement_relationships_account.dart';
part 'model/error.dart';
part 'model/error_source.dart';
part 'model/forgot_password_request.dart';
part 'model/forgot_password_request_meta.dart';
part 'model/generate_product_token_request.dart';
part 'model/generate_product_token_request_data.dart';
part 'model/generate_product_token_request_data_attributes.dart';
part 'model/generate_product_token_response.dart';
part 'model/generate_token_request.dart';
part 'model/generate_token_request_data.dart';
part 'model/generate_token_request_data_attributes.dart';
part 'model/generate_token_request_data_attributes_meta.dart';
part 'model/generate_token_response.dart';
part 'model/generate_user_token_request.dart';
part 'model/generate_user_token_response.dart';
part 'model/group.dart';
part 'model/group_attributes.dart';
part 'model/group_relationships.dart';
part 'model/group_relationships_account.dart';
part 'model/group_relationships_licenses.dart';
part 'model/group_relationships_machines.dart';
part 'model/group_relationships_owners.dart';
part 'model/group_relationships_users.dart';
part 'model/increment_license_usage_request.dart';
part 'model/increment_license_usage_request_meta.dart';
part 'model/increment_license_usage_response.dart';
part 'model/kill_process_response.dart';
part 'model/license.dart';
part 'model/license_attributes.dart';
part 'model/license_entitlement.dart';
part 'model/license_entitlement_relationships.dart';
part 'model/license_entitlement_relationships_license.dart';
part 'model/license_file.dart';
part 'model/license_file_attributes.dart';
part 'model/license_file_relationships.dart';
part 'model/license_relationships.dart';
part 'model/license_relationships_account.dart';
part 'model/license_relationships_group.dart';
part 'model/license_relationships_machines.dart';
part 'model/license_relationships_policy.dart';
part 'model/license_relationships_product.dart';
part 'model/license_relationships_user.dart';
part 'model/list_entitlements_response.dart';
part 'model/list_groups_response.dart';
part 'model/list_license_entitlements_response.dart';
part 'model/list_licenses_expires_parameter.dart';
part 'model/list_licenses_response.dart';
part 'model/list_machines_response.dart';
part 'model/list_policies_response.dart';
part 'model/list_policy_entitlements_response.dart';
part 'model/list_processes_response.dart';
part 'model/list_products_response.dart';
part 'model/list_second_factors_response.dart';
part 'model/list_tokens_bearer_parameter.dart';
part 'model/list_tokens_response.dart';
part 'model/list_users_response.dart';
part 'model/machine.dart';
part 'model/machine_attributes.dart';
part 'model/machine_file.dart';
part 'model/machine_file_relationships.dart';
part 'model/machine_file_relationships_machine.dart';
part 'model/machine_relationships.dart';
part 'model/machine_relationships_account.dart';
part 'model/machine_relationships_group.dart';
part 'model/machine_relationships_license.dart';
part 'model/machine_relationships_processes.dart';
part 'model/machine_relationships_product.dart';
part 'model/machine_relationships_user.dart';
part 'model/pagination_links.dart';
part 'model/pagination_links_meta.dart';
part 'model/ping_machine_response.dart';
part 'model/ping_process_response.dart';
part 'model/policy.dart';
part 'model/policy_attributes.dart';
part 'model/policy_entitlement.dart';
part 'model/policy_entitlement_attributes.dart';
part 'model/policy_entitlement_relationships.dart';
part 'model/policy_entitlement_relationships_account.dart';
part 'model/policy_entitlement_relationships_entitlement.dart';
part 'model/policy_entitlement_relationships_policy.dart';
part 'model/policy_relationships.dart';
part 'model/policy_relationships_account.dart';
part 'model/policy_relationships_entitlements.dart';
part 'model/policy_relationships_licenses.dart';
part 'model/policy_relationships_pool.dart';
part 'model/policy_relationships_product.dart';
part 'model/process.dart';
part 'model/process_attributes.dart';
part 'model/process_relationships.dart';
part 'model/process_relationships_account.dart';
part 'model/process_relationships_license.dart';
part 'model/process_relationships_machine.dart';
part 'model/process_relationships_product.dart';
part 'model/product.dart';
part 'model/product_attributes.dart';
part 'model/product_relationships.dart';
part 'model/product_relationships_account.dart';
part 'model/product_relationships_licenses.dart';
part 'model/product_relationships_machines.dart';
part 'model/product_relationships_policies.dart';
part 'model/product_relationships_tokens.dart';
part 'model/product_relationships_users.dart';
part 'model/regenerate_token_response.dart';
part 'model/reinstate_license_response.dart';
part 'model/related_links.dart';
part 'model/renew_license_response.dart';
part 'model/reset_license_usage_response.dart';
part 'model/reset_machine_response.dart';
part 'model/reset_user_password_request.dart';
part 'model/reset_user_password_request_meta.dart';
part 'model/reset_user_password_response.dart';
part 'model/retrieve_entitlement_response.dart';
part 'model/retrieve_group_response.dart';
part 'model/retrieve_license_response.dart';
part 'model/retrieve_machine_response.dart';
part 'model/retrieve_policy_response.dart';
part 'model/retrieve_process_response.dart';
part 'model/retrieve_product_response.dart';
// BEGIN MANUALLY MODIFIED AFTER OPENAPI-GENERATOR RAN
part 'model/retrieve_profile_response.dart';
// END MANUALLY MODIFIED AFTER OPENAPI-GENERATOR RAN
part 'model/retrieve_second_factor_response.dart';
part 'model/retrieve_token_response.dart';
part 'model/retrieve_user_response.dart';
part 'model/second_factor.dart';
part 'model/second_factor_attributes.dart';
part 'model/second_factor_relationships.dart';
part 'model/second_factor_relationships_account.dart';
part 'model/second_factor_relationships_user.dart';
part 'model/self_links.dart';
part 'model/spawn_process_request.dart';
part 'model/spawn_process_request_data.dart';
part 'model/spawn_process_request_data_attributes.dart';
part 'model/spawn_process_request_data_relationships.dart';
part 'model/spawn_process_request_data_relationships_machine.dart';
part 'model/spawn_process_request_data_relationships_machine_data.dart';
part 'model/spawn_process_response.dart';
part 'model/suspend_license_response.dart';
part 'model/token.dart';
part 'model/token_attributes.dart';
part 'model/token_relationships.dart';
part 'model/token_relationships_account.dart';
part 'model/token_relationships_account_data.dart';
part 'model/token_relationships_bearer.dart';
part 'model/token_relationships_bearer_data.dart';
part 'model/unban_user_response.dart';
part 'model/update_entitlement_request.dart';
part 'model/update_entitlement_request_data.dart';
part 'model/update_entitlement_request_data_attributes.dart';
part 'model/update_entitlement_response.dart';
part 'model/update_group_request.dart';
part 'model/update_group_request_data.dart';
part 'model/update_group_request_data_attributes.dart';
part 'model/update_group_response.dart';
part 'model/update_license_request.dart';
part 'model/update_license_request_data.dart';
part 'model/update_license_request_data_attributes.dart';
part 'model/update_license_response.dart';
part 'model/update_machine_request.dart';
part 'model/update_machine_request_data.dart';
part 'model/update_machine_request_data_attributes.dart';
part 'model/update_machine_response.dart';
part 'model/update_policy_request.dart';
part 'model/update_policy_request_data.dart';
part 'model/update_policy_request_data_attributes.dart';
part 'model/update_policy_response.dart';
part 'model/update_process_request.dart';
part 'model/update_process_request_data.dart';
part 'model/update_process_request_data_attributes.dart';
part 'model/update_process_response.dart';
part 'model/update_product_request.dart';
part 'model/update_product_request_data.dart';
part 'model/update_product_request_data_attributes.dart';
part 'model/update_product_response.dart';
part 'model/update_second_factor_request.dart';
part 'model/update_second_factor_request_data.dart';
part 'model/update_second_factor_request_data_attributes.dart';
part 'model/update_second_factor_request_meta.dart';
part 'model/update_second_factor_response.dart';
part 'model/update_user_password_request.dart';
part 'model/update_user_password_request_meta.dart';
part 'model/update_user_password_response.dart';
part 'model/update_user_request.dart';
part 'model/update_user_request_data.dart';
part 'model/update_user_request_data_attributes.dart';
part 'model/update_user_response.dart';
part 'model/user.dart';
part 'model/user_attributes.dart';
part 'model/user_relationships.dart';
part 'model/user_relationships_account.dart';
part 'model/user_relationships_group.dart';
part 'model/user_relationships_licenses.dart';
part 'model/user_relationships_machines.dart';
part 'model/user_relationships_products.dart';
part 'model/user_relationships_tokens.dart';
part 'model/validate_license_key_request.dart';
part 'model/validate_license_key_request_meta.dart';
part 'model/validate_license_key_response.dart';
part 'model/validate_license_request.dart';
part 'model/validate_license_request_meta.dart';
part 'model/validate_license_request_meta_scope.dart';
part 'model/validate_license_response.dart';
part 'model/validate_license_response_meta.dart';
part 'model/validate_license_response_meta_scope.dart';
part 'model/webhook_event.dart';
part 'model/webhook_event_attributes.dart';
part 'model/webhook_event_relationships.dart';
part 'model/webhook_event_relationships_account.dart';


/// An [ApiClient] instance that uses the default values obtained from
/// the OpenAPI specification file.
var defaultApiClient = ApiClient();

const _delimiters = {'csv': ',', 'ssv': ' ', 'tsv': '\t', 'pipes': '|'};
const _dateEpochMarker = 'epoch';
const _deepEquality = DeepCollectionEquality();
final _dateFormatter = DateFormat('yyyy-MM-dd');
final _regList = RegExp(r'^List<(.*)>$');
final _regSet = RegExp(r'^Set<(.*)>$');
final _regMap = RegExp(r'^Map<String,(.*)>$');

bool _isEpochMarker(String? pattern) => pattern == _dateEpochMarker || pattern == '/$_dateEpochMarker/';
