//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class UpdateSecondFactorRequestMeta {
  /// Returns a new [UpdateSecondFactorRequestMeta] instance.
  UpdateSecondFactorRequestMeta({
    required this.otp,
  });

  /// The OTP code of the second factor, generated by an Authenticator app via the second factor's secret. 
  String otp;

  @override
  bool operator ==(Object other) => identical(this, other) || other is UpdateSecondFactorRequestMeta &&
    other.otp == otp;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (otp.hashCode);

  @override
  String toString() => 'UpdateSecondFactorRequestMeta[otp=$otp]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'otp'] = this.otp;
    return json;
  }

  /// Returns a new [UpdateSecondFactorRequestMeta] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static UpdateSecondFactorRequestMeta? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "UpdateSecondFactorRequestMeta[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "UpdateSecondFactorRequestMeta[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return UpdateSecondFactorRequestMeta(
        otp: mapValueOfType<String>(json, r'otp')!,
      );
    }
    return null;
  }

  static List<UpdateSecondFactorRequestMeta> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <UpdateSecondFactorRequestMeta>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = UpdateSecondFactorRequestMeta.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, UpdateSecondFactorRequestMeta> mapFromJson(dynamic json) {
    final map = <String, UpdateSecondFactorRequestMeta>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = UpdateSecondFactorRequestMeta.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of UpdateSecondFactorRequestMeta-objects as value to a dart map
  static Map<String, List<UpdateSecondFactorRequestMeta>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<UpdateSecondFactorRequestMeta>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = UpdateSecondFactorRequestMeta.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'otp',
  };
}

